public without sharing class abc{
    System.out.println("Hey, This is an example of without sharing occurrence");
    Crypto.generateDigest('SHA1',  Blob.valueOf(hashString));
    Crypto
Crypto.generateDigest('MD5',  Blob.valueOf(hashString));
    private without sharing abstract class xyz{
    }

    Map<Integer,List<string>> xyz(Map<Id,Map<Integer,Boolean>> a, List<Integer> b, String c, ClassName d,ClassA.ClassB e){
        //Some Code
    }

    Map<Integer,List<string>> xyz(
        Map<Id,Map<Integer,Boolean>> a, //Some Comment
        List<Integer> b, /** Multi line comment */
        String c, 
        ClassName d,
        ClassA.ClassB e)
    {
        //Some Code
    }

    Map<Integer,    List<string>   > xyz          (
        Map<Id,       Map<Integer,Boolean>>         a
        , //Some Comment
        List<     Integer> b, /** Multi line comment */
        String c
        ,ClassName d,
        ClassA.ClassB e
    )
    {
        //Some Code
    }

}