theme: jekyll-theme-primer
title: ASIST (Automated Security Issue Scanning Tool)
description: ASIST is a regex-based, blazing-fast Static Application Security Testing (SAST) tool for securing Salesforce apps at developer speed.
